Sprint 5 login 16 bit 20/21 Реализовать логику авторизации / Подключить API Практикума для авторизации пользователя
ivanK333/pac-man pull request #18
Opened 2023-08-20 11:10 UTC by MIdkhat

### Какую задачу решаем
16BIT-20/21 Реализовать логику авторизации / Подключить API Практикума для авторизации пользователя

добавлен AuthAPI для signin/signout и возможно register (create)
добавлен AuthController для signin, signout, fetchUser, сюда же можно добавить signup
в App.tsx добавлен hook для isAuthorised
Проверка осуществляется через AuthController.FetchUser, если юзер воpвращается, то авторизация прошла и апп переходит на страницу игры, если не получилось залогиниться то возвращается причина ошибки и она попадает в форму логина

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-08-20 15:30 UTC, zubastu approved these changes
Отличная работа! Добавить нечего

2023-08-21 08:05 UTC, PolinaKuksova2022 approved these changes
Все супер!

2023-08-23 15:29 UTC, Olegas requested changes
Добрый день.
Есть вопросы и замечания по коду.
Написал подробно в комментариях

2023-08-23 15:29 UTC, Olegas commented on packages/client/src/api/AuthAPI.ts
> +  create = undefined;
А зачем это? Если не нужно - просто удалите

2023-08-23 15:29 UTC, Olegas commented on packages/client/src/controllers/AuthController.ts
> +// });
Не надо оставлять в репозитории закомментированный код

2023-08-23 15:29 UTC, Olegas commented on packages/client/src/controllers/AuthController.ts
> +  // }
Не надо оставлять закомментированный код

2023-08-23 15:29 UTC, Olegas commented on packages/client/src/controllers/AuthController.ts
> +      localStorage.setItem('isAuthenticated', 'false');
Почему false? Мы же успешно авторизовались после регистрации сразу?

2023-08-23 15:29 UTC, Olegas commented on packages/client/src/controllers/AuthController.ts
> +        localStorage.setItem('isAuthenticated', 'false');
А где используется? Где чтение этого параметра?

2023-08-23 23:15 UTC, MIdkhat commented on packages/client/src/api/AuthAPI.ts
> +  create = undefined;
убрал

2023-08-23 23:15 UTC, MIdkhat commented on packages/client/src/controllers/AuthController.ts
> +// });
убрал

2023-08-23 23:15 UTC, MIdkhat commented on packages/client/src/controllers/AuthController.ts
> +      localStorage.setItem('isAuthenticated', 'false');
Исправил

2023-08-23 23:15 UTC, MIdkhat commented on packages/client/src/controllers/AuthController.ts
> +        localStorage.setItem('isAuthenticated', 'false');
это было решение тимлида хранить состояние авторизации в localStorage, в данный момент не используется, но может быть использован другими членами команды, тут он лежит, что бы любой мог при чтении кода видеть, что это значение сохраненно и использовать в другой части кода.

2023-08-23 23:15 UTC, MIdkhat commented on packages/client/src/controllers/AuthController.ts
> +  // }
Убрал. Оставлял как шаблон для того члена команды, кто будет делать signup часть , что бы код был в едином стиле.

2023-08-24 12:16 UTC, Olegas approved these changes
Работа принята, спасибо

2023-08-24 12:33 UTC, merged