Zubastu/16bit 37 подключить api для смены аватара пользователя
ivanK333/pac-man pull request #26
Opened 2023-08-23 19:41 UTC by zubastu

### Последняя задача из профиля
Подключил апи для смены аватара
Задача для сдачи на ревью пятого спринта
1.Верстка страницы профиля
2.Подключить API изменения пароля
3.Верстка компонента изменеия аватара
4.Подключение API для изменения аватара(текущая задача)
Так же подключил API для изменения профиля

### Скриншоты/видяшка (если есть)
![image](https://github.com/ivanK333/pac-man/assets/79757684/21da41b6-235e-49b8-b2dd-a7a0344a8a9c)
### TBD (если есть)

2023-08-24 15:01 UTC, MIdkhat approved these changes

2023-08-24 16:25 UTC, PolinaKuksova2022 approved these changes
Отличная работа :)

2023-08-24 16:36 UTC, zubastu commented on packages/client/src/components/Modal/styles.module.scss
> +  height: calc(100% - 95px);
Modal согласно макету имеет отступы сверху 55px и снизу 40px я сделал его высотой блока в который он будет помещен, учитывая что отступ от хедера по макету 55px, в Modal можно поместить любой контент, любую форму

2023-08-24 16:38 UTC, zubastu commented on packages/client/src/components/Modal/Modal.tsx
> +        className={styles.contentContainer}
он нужен для 
![image](https://github.com/ivanK333/pac-man/assets/79757684/1e1c06b9-191c-45a0-84de-b87014d674f1)

2023-08-24 16:48 UTC, zubastu commented on packages/client/src/components/Avatar/Avatar.tsx
>          <div className={styles.hoverOverlay}>
Поправил)

2023-08-24 16:52 UTC, zubastu commented on packages/client/src/components/Avatar/Avatar.tsx
>        <section className={styles.wrapper}>
![image](https://github.com/ivanK333/pac-man/assets/79757684/16ce03a0-b8a7-4a8c-a587-f57b8980e451)
Исправил )

2023-08-25 07:11 UTC, Brarion requested changes
Супер, парочка замечаний небольших есть, подправь, пожалуйста, для красоты :)

2023-08-25 09:16 UTC, zubastu commented on packages/client/src/pages/Profile/Profile.tsx
> +      ) : null}
Подправил, но такой подход приводит к багам, если условие будет 0 или NaN то перед компонентом будет 0 либо NaN

2023-08-25 09:16 UTC, zubastu commented on packages/client/src/components/Modal/Modal.tsx
> +        className={styles.contentContainer}
Убрал закрытие по клику на пустое пространство

2023-08-25 10:07 UTC, PolinaKuksova2022 commented on packages/client/src/components/Modal/Modal.tsx
> +        className={styles.contentContainer}
Он нужен для закрытия? МБ тогда не селектор добавлять, а id?

2023-08-25 10:41 UTC, Brarion commented on packages/client/src/pages/Profile/Profile.tsx
> +      ) : null}
Согласен, но в данном случае `isOpenModal` имеет тип `boolean`, поэтому тут ничего страшного нет

2023-08-25 10:42 UTC, Brarion approved these changes
:fire:

2023-08-25 11:26 UTC, merged