Zubastu/16bit 24 сверстать экраны форума
ivanK333/pac-man pull request #29
Opened 2023-08-28 15:27 UTC by zubastu

### Какую задачу решаем
Верстка форума
Написал структуру форума, динамический маршрут для топиков
### Скриншоты/видяшка (если есть)
![image](https://github.com/ivanK333/pac-man/assets/79757684/f7698cc5-b1ec-493d-9b92-e1006b953328)
![image](https://github.com/ivanK333/pac-man/assets/79757684/3d6d5ae7-b5ca-4429-8558-7e3b0e5e541d)
![image](https://github.com/ivanK333/pac-man/assets/79757684/052b762f-c428-4e1e-8412-066a3a3202e8)
![image](https://github.com/ivanK333/pac-man/assets/79757684/1503c663-4434-4230-91fe-496611f8e447)

### TBD (если есть)

2023-08-30 10:35 UTC, PolinaKuksova2022 approved these changes
Огромная работа!
Forum получился самой сложной страницей в которую входит полноценный чат. 
Илья отлично справился, продумал удобное общение пользователей, вынес отдельно компоненты, которые удобно переиспользовать, сделал мини-роутинг для переключения с основной странице форума на страницу обсуждения конкретного топика и добавил модалку для создания нового топика. 
Работа выполнена на высшем уровне 👏👏👏

2023-08-30 10:35 UTC, PolinaKuksova2022 commented on packages/client/src/components/TopicMessage/TopicMessage.tsx
> +              {comments && comments.length > 0
Зачем проверять comments && comments.length > 0? разве не достаточно просто comments?

2023-08-30 10:35 UTC, PolinaKuksova2022 commented on packages/client/src/components/TopicMessage/TopicMessage.tsx
> +                  : null}
Можно проще) Плюс избавиться от одной обертки comments vs connetsContainer
![image](https://github.com/ivanK333/pac-man/assets/108727043/b9269e74-c6ef-4d73-8c37-648459944a38)

2023-08-30 10:35 UTC, PolinaKuksova2022 commented on packages/client/src/components/TopicMessage/TopicMessage.tsx
> +          {isShow && (
Здорово придумал убирать комменты!

2023-08-30 10:35 UTC, PolinaKuksova2022 commented on packages/client/src/pages/Forum/Forum.tsx
> +  const handleCloseModal = () => {
Можно проще)
![image](https://github.com/ivanK333/pac-man/assets/108727043/0e3640da-2c89-47c0-8e82-08cbf13d709e)

2023-08-30 10:35 UTC, PolinaKuksova2022 commented on packages/client/src/pages/Forum/styles.module.scss
> +.containerWithImage {
Где применяется этот селектор?

2023-08-30 10:35 UTC, PolinaKuksova2022 commented on packages/client/src/pages/Forum/styles.module.scss
> +.link {
Где применяется этот селектор?

2023-08-30 10:35 UTC, PolinaKuksova2022 commented on packages/client/src/pages/Forum/styles.module.scss
> +.linkActive {
Где применяется этот селектор?

2023-08-30 10:35 UTC, PolinaKuksova2022 commented on packages/client/src/pages/Forum/styles.module.scss
> +.forumNavigation {
Где применяется этот селектор?

2023-08-30 10:35 UTC, PolinaKuksova2022 commented on packages/client/src/pages/Topic/Topic.tsx
> +            autoFocus={true}
Можно убрать autoFocus

2023-08-30 10:35 UTC, PolinaKuksova2022 commented on packages/client/src/pages/Topic/Topic.tsx
> +  const history = useNavigate();
Удобный роутинг)

2023-08-30 10:35 UTC, PolinaKuksova2022 commented on packages/client/src/pages/Topic/Topic.tsx
> +  const history = useNavigate();
Удобный роутинг)

2023-08-30 10:35 UTC, PolinaKuksova2022 commented on packages/client/src/pages/Topic/Topic.tsx
> +  const history = useNavigate();
Удобный роутинг)

2023-08-30 10:35 UTC, PolinaKuksova2022 commented on packages/client/src/pages/Topic/Topic.tsx
> +  const history = useNavigate();
Удобный роутинг)

2023-08-30 10:35 UTC, PolinaKuksova2022 commented on packages/client/src/pages/Topic/styles.module.scss
> +  padding: 0;
font-style: normal;
font-weight: 400;
line-height: normal;
можно убрать, они применяются по дефолту

2023-08-30 10:35 UTC, PolinaKuksova2022 commented on packages/client/src/pages/Topic/styles.module.scss
> +  width: 100%;
Проверь меня, вроде  width: 100%; можно убрать

2023-08-30 10:35 UTC, PolinaKuksova2022 commented on packages/client/src/pages/Topic/styles.module.scss
> +  width: 100%;
Проверь меня, вроде  width: 100%; можно убрать

2023-08-30 10:35 UTC, PolinaKuksova2022 commented on packages/client/src/pages/Topic/styles.module.scss
> +  width: 100%;
Проверь меня, вроде  width: 100%; можно убрать

2023-08-30 10:35 UTC, PolinaKuksova2022 commented on packages/client/src/components/CommentItem/CommentItem.tsx
> +      <div className={styles.headingContainer}>
Думаю семантически можно div заменить на section

2023-08-30 10:35 UTC, PolinaKuksova2022 commented on packages/client/src/components/CommentItem/CommentItem.tsx
> +          <p className={styles.text}>{comment}</p>
Тут можно избавиться от div или p?

2023-08-30 10:58 UTC, zubastu commented on packages/client/src/components/TopicCreationForm/TopicCreationForm.tsx
> +      <Input
поправлю)

2023-08-30 10:58 UTC, zubastu commented on packages/client/src/components/TopicCreationForm/TopicCreationForm.tsx
> +        bottomText="don't want to create?"
Поправлю)

2023-08-30 10:59 UTC, zubastu commented on packages/client/src/components/TopicCreationForm/styles.module.scss
> +
забыл запустить, поправлю)

2023-08-30 10:59 UTC, zubastu commented on packages/client/src/components/TopicCreationForm/styles.module.scss
> +.messageInput {
я думаю тут сделать textarea так как текс сообщения может быть очень длинным

2023-08-30 11:00 UTC, zubastu commented on packages/client/src/components/TopicForm/TopicForm.tsx
> +    formMethods.formState.isValid && onSubmit(data);
Сейчас на форме нет валидации

2023-08-30 11:01 UTC, zubastu commented on packages/client/src/components/TopicForm/TopicForm.tsx
> +  }, [formMethods.setFocus]);
я использую форму в нескольких места, в комментариях нужен фокус только при развертывании списка комментариев

2023-08-30 11:02 UTC, zubastu commented on packages/client/src/components/TopicForm/styles.module.scss
> +  font-weight: 300;
поправлю

2023-08-30 11:02 UTC, zubastu commented on packages/client/src/pages/Topics/Topics.tsx
поменяю

2023-08-30 11:03 UTC, zubastu commented on packages/client/src/pages/Topics/Topics.tsx
> +  handleOpenModal: () => void;
это необязательно

2023-08-30 11:04 UTC, zubastu commented on packages/client/src/components/TopicItem/TopicItem.tsx
> +        <img src={blueGhostImage} alt="Ghost" />
я думал об этом, но когда тем становится больше трех, они очень сильно отвлекают

2023-08-30 11:13 UTC, zubastu commented on packages/client/src/pages/Topics/Topics.tsx
> +        <div className={styles.topicList}>
убрал лишний, спасибо

2023-08-30 11:15 UTC, zubastu commented on packages/client/src/components/TopicItem/styles.module.scss
> +}
не используется, остался после переноса AvatarImage в отдельный компонент

2023-08-30 11:17 UTC, zubastu commented on packages/client/src/components/TopicMessage/TopicMessage.tsx
> +              {comments && comments.length > 0
comments это массив, если проверить что он определен но не имеет содержания, то функция map выкинет ошибку, и логнически нет смысла итерироваться по пустому массиву

2023-08-30 11:20 UTC, zubastu commented on packages/client/src/components/TopicMessage/TopicMessage.tsx
> +                  : null}
Исправил, спасибо

2023-08-30 11:21 UTC, zubastu commented on packages/client/src/pages/Forum/Forum.tsx
> +  const handleCloseModal = () => {
эти методы будут потом отправлять экшены в стор

2023-08-30 11:23 UTC, zubastu commented on packages/client/src/pages/Forum/styles.module.scss
> +.containerWithImage {
до правок внутреннего роутинга, были страницы с зеленым призраком, теперь их нет, удалю селектор

2023-08-30 11:24 UTC, zubastu commented on packages/client/src/pages/Topic/Topic.tsx
> +            autoFocus={true}
я бы оставил

2023-08-30 11:25 UTC, zubastu commented on packages/client/src/pages/Topic/styles.module.scss
> +  padding: 0;
спасибо, поправил

2023-08-30 11:28 UTC, zubastu commented on packages/client/src/pages/Topic/styles.module.scss
> +  width: 100%;
да, убрал, спасибо

2023-08-30 11:29 UTC, zubastu commented on packages/client/src/components/CommentItem/CommentItem.tsx
> +      <div className={styles.headingContainer}>
исправил, спасибо

2023-08-30 11:29 UTC, zubastu commented on packages/client/src/components/CommentItem/CommentItem.tsx
> +          <p className={styles.text}>{comment}</p>
div оборачивает сообщение, он понадобится когда будут лайки и эмодзи

2023-08-30 13:12 UTC, PolinaKuksova2022 commented on packages/client/src/components/TopicForm/TopicForm.tsx
Да. но просто из названия TopicFopm не понятно для чего нужен этот компонент

2023-08-30 13:14 UTC, PolinaKuksova2022 commented on packages/client/src/components/TopicForm/TopicForm.tsx
> +  }, [formMethods.setFocus]);
А он так и будет работать, без useEffect, проверь)

2023-08-31 05:19 UTC, IvanPeleshok commented on packages/client/src/assets/styles/_mixins.scss
> +}
Рекомендация: оставлять пустую строку в конце файла и вот почему:
https://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file

2023-08-31 05:23 UTC, IvanPeleshok commented on packages/client/src/components/AvatarImage/AvatarImage.tsx
> +        size === Size.normal
Предлагаю внедрить либу [classnames](https://www.npmjs.com/package/classnames)
Намного удобнее и гибче получится использовать классы по условиям
Примеры: 
https://medium.com/2359media/why-react-classnames-is-a-lifesaver-and-how-you-should-use-it-if-you-arent-already-b25a44ed5603#:~:text=Thankfully%20with%20classnames%2C%20I%20can%20simplify%20it%20to%3A

```
className={classnames('avatar_image__wrapper', {
  [styles.imageContainer]: size === Size.normal
)}
```

2023-08-31 05:23 UTC, IvanPeleshok commented on packages/client/src/components/AvatarImage/AvatarImage.tsx
> +        size === Size.normal
Давайте поправить в рамках этого PR похожие моменты

2023-08-31 05:24 UTC, IvanPeleshok commented on packages/client/src/components/AvatarImage/AvatarImage.tsx
> +      {image === 'null' || !image || image === defaultImage ? (
Предлагаю вынести в переменную данное условие

2023-08-31 05:25 UTC, IvanPeleshok commented on packages/client/src/components/Header/Header.tsx
> +  const handleLogout = () => {
Предлагаю разделять блоки для того, чтобы читалось получше

2023-08-31 05:26 UTC, IvanPeleshok commented on packages/client/src/assets/styles/_mixins.scss
> +}
И в других файлах, где нет пустой строки

2023-08-31 05:30 UTC, IvanPeleshok commented on packages/client/src/components/TopicMessage/TopicMessage.tsx
> +              {comments && comments.length > 0
Предлагаю воспользоваться следующей конструкцией: `comments?.length`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

2023-08-31 05:32 UTC, IvanPeleshok commented on packages/client/src/components/TopicMessage/TopicMessage.tsx
> +                ? comments.map((comment) => (
В подобных условиях лучше не использовать тернарный оператор, а воспользоваться &&, чтобы не возвращать `null`

2023-08-31 05:34 UTC, IvanPeleshok commented on packages/client/src/pages/Topic/Topic.tsx
> +            topic.messages.map((message) => (
`topic?.messages?.map` - условие в одну строку

2023-08-31 05:35 UTC, IvanPeleshok requested changes
Классная работа, но есть небольшие замечания
Необходима доработка

2023-08-31 05:36 UTC, IvanPeleshok commented on packages/client/src/components/Header/Header.tsx
> +  const handleLogout = () => {
Предлагаю поправить аналогичные моменты во всём PR

2023-08-31 11:01 UTC, zubastu commented on packages/client/src/components/TopicMessage/TopicMessage.tsx
> +                ? comments.map((comment) => (
В данном условии идет сравнение на определение массива && длинаа массива(выходит число) если число будет NaN или 0 то это условие отрендерит на страницу 0 либо NaN

2023-08-31 12:25 UTC, zubastu commented on packages/client/src/components/AvatarImage/AvatarImage.tsx
> +      {image === 'null' || !image || image === defaultImage ? (
поправил

2023-08-31 12:33 UTC, zubastu commented on packages/client/src/pages/Topic/Topic.tsx
> +            topic.messages.map((message) => (
исправил

2023-08-31 12:41 UTC, zubastu commented on packages/client/src/assets/styles/_mixins.scss
> +}
Конфиг stylelint написал наш тимлид, спрошу его добавить правило

2023-08-31 14:49 UTC, IvanPeleshok approved these changes
Замечательная работа, хорошо потрудились!
Апрув :)

2023-08-31 15:49 UTC, merged