добавлена основная механика игры на canvas
ivanK333/pac-man pull request #34
Opened 2023-08-30 00:47 UTC by razuvaevcr

### Какую задачу решаем
Создан основной loop игры на canvas-api.
Создана карта.
Нарисованы хитбоксы стен и персонажа (pacman).
Создан механизм расчета столкновений (коллизия стена/pacman).

### Скриншоты/видяшка (если есть)
<img width="530" alt="Снимок экрана 2023-08-30 в 03 43 11" src="https://github.com/ivanK333/pac-man/assets/51992031/25e3f1b1-56f7-4afe-a470-6bc6a8ada169">

2023-08-30 13:28 UTC, MIdkhat approved these changes

2023-08-30 13:38 UTC, razuvaevcr commented on packages/client/src/engine/GameCanvas.tsx
> +    for (let i = 0; i < map.length; i++) {
Суть в том, что в дальнейшем я планирую допилить эти оба варианта и сделать что-то среднее, а алгоритм по определению углов как раз мне в этом очень сильно поможет))

2023-08-30 13:41 UTC, razuvaevcr commented on packages/client/src/engine/GameCanvas.tsx
> +      <canvas ref={canvasRef} id="canvas" width="420" height="460"></canvas>
Размеры оставил (пока) статические, так как есть проблемы с изменением скорости и размеров блока. Пример: при изменении скорости пакмана не каждое столкновение выдает коллизию, и персонаж просто проходит сквозь стену.

2023-08-30 13:50 UTC, razuvaevcr commented on packages/client/src/engine/GameCanvas.tsx
> +  const redraw = (ctx: CanvasRenderingContext2D) => {
логика такая: перерисовка background происходит из-за предыдущего положения пакмана на канвасе (грубо говоря, он оставляет за собой след из предыдущих состояний), а перерисовка background тянет за собой перерисовку карты

2023-08-31 05:47 UTC, IvanPeleshok commented on packages/client/src/engine/GameCanvas.tsx
Предлагаю вынести всю логику в класс Game, а в компоненте создавать экземпляр класса и дёргать методы

Таким образом, мы получаем меньше связей, проще тестирование и гибкость

Класс можно построить на принципах singeltor, чтобы был только один экземпляр класса
https://www.dofactory.com/javascript/design-patterns/singleton

2023-08-31 05:49 UTC, IvanPeleshok commented on packages/client/src/engine/GameCanvas.tsx
> +        case 'ArrowRight':
ArrowRight, ArrowLeft, ArrowLeft, ArrowDown - выносим в константы или enum
Аналогично и right, left, up, down и переиспользуем в других местах

2023-08-31 05:51 UTC, IvanPeleshok commented on packages/client/src/engine/GameCanvas.tsx
> +      !Number.isInteger(rightCoord) ||
Рекомендация: подобные условия принято разделять со следующей строки
```
if (
  va1
  || va2
  || var3
) {}
```

2023-08-31 05:51 UTC, IvanPeleshok commented on packages/client/src/engine/GameCanvas.tsx
> +  const checkCollision = (dir: string) => {
Предлагаю не сокращать названия переменных

2023-08-31 05:53 UTC, IvanPeleshok commented on packages/client/src/engine/GameCanvas.tsx
> +    switch (dir) {
Данную конструкцию можно сократить, если возвращать значение функции внутри case
```
case (direction) {
  case RIGHT:
    return collision.rightBlock ? true : false
```

2023-08-31 05:57 UTC, IvanPeleshok commented on packages/client/src/engine/GameCanvas.tsx
> +        if (map[i][j] === 1) {
Т.к код не выглядит простым, предлагаю такие блоки покрывать комментариями в формате: что тут происходит?
Пример: 
```
// рисуем начальный полигон 
```

2023-08-31 05:59 UTC, IvanPeleshok requested changes
Классная работа
Хорошее владение канвасом, вы молодец :)

Но есть замечание: предлагаю вынести функционал игры в класс
В компоненте же дёргать методы класса

2023-09-04 17:05 UTC, merged

2023-09-04 17:28 UTC, IvanPeleshok commented
@razuvaevcr 
Привет 
Без апрува нельзя мержить задачку
Необходимы доработки, потом будет апрув и после него только мерж

2023-09-04 18:03 UTC, razuvaevcr commented
@IvanPeleshok
Привет! Я думал, что это не критичные замечания, и мы с командой внесем правки по ходу написания полноценного движка, так как есть еще куча идей и вариантов решения описанной тобой проблемы.

2023-09-04 19:18 UTC, razuvaevcr commented
@IvanPeleshok
Есть ли возможность зачета задания при нынешнем его состоянии? Или необходимы правки в этой ветке?

2023-09-04 19:48 UTC, IvanPeleshok commented
@razuvaevcr
Необходимы доработки 
Лучше сразу сделать так, чтобы функционал был гибок к модификации (с учетом, что у вас есть мысли о его доработке)