внесены изменения в соответствии с ревью
ivanK333/pac-man pull request #40
Opened 2023-09-05 13:52 UTC by razuvaevcr

### Какую задачу решаем
Внесенные изменения после ревью.

### Скриншоты/видяшка (если есть)
<img width="942" alt="Снимок экрана 2023-09-05 в 16 51 24" src="https://github.com/ivanK333/pac-man/assets/51992031/38ed9030-c4bc-4cd3-899c-e21a05168725">

### TBD (если есть)

2023-09-05 14:05 UTC, zubastu approved these changes
аппрув )

2023-09-05 15:15 UTC, MIdkhat approved these changes

2023-09-05 19:01 UTC, IvanPeleshok commented on packages/client/src/engine/Game.tsx
Правильнее будет прокинуть аргументами в конструктор класса все необходимые данные и дергать их

2023-09-05 19:01 UTC, IvanPeleshok commented on packages/client/src/engine/GameCanvas.tsx
>      const keyboardHandler = (e: KeyboardEvent) => {
Выносим в класс игры

2023-09-05 19:06 UTC, IvanPeleshok commented on packages/client/src/engine/Pacman.tsx
Аналогичная рекомендация про конструктор класса (намного удобнее и гибче к дальнейшей разработке)

2023-09-05 19:07 UTC, IvanPeleshok commented on packages/client/src/engine/Game.tsx
Методам лучше давать явные модификаторы доступа public / private и т.п

2023-09-05 19:10 UTC, IvanPeleshok requested changes
Отличная работа!

Предлагаю сделать следующие доработки и вообще будет огонь!

2023-09-05 19:13 UTC, razuvaevcr commented on packages/client/src/engine/Game.tsx
То есть, все состояния "отдать" классам? (грубо говоря переписать с хуков на классы полностью)

2023-09-05 19:52 UTC, IvanPeleshok commented on packages/client/src/engine/Game.tsx
> То есть, все состояния "отдать" классам? (грубо говоря, переписать с хуков на классы полностью)

Хуки сами по себе оставляем, но выносим функционал внутри колбека в класс

Все элементы управлениям (сеттеры состояния и контекст канваса прокидываем в конструктор)
Таким образом, в хуках будет что-то следующее:
```
useEffect(() => doSomething(args), [deps])
```

2023-09-07 07:14 UTC, IvanPeleshok commented on packages/client/src/engine/Game.tsx
> +  constructor(props: any) {
Давай опишем тип параметра

2023-09-07 07:15 UTC, IvanPeleshok commented on packages/client/src/engine/Pacman.tsx
> +  constructor(props: any) {
Давай опишем тип параметра

2023-09-07 07:15 UTC, IvanPeleshok commented on packages/client/src/engine/Pacman.tsx
> +  pacmanState: any;
Хотелось бы описание типа

2023-09-07 07:16 UTC, IvanPeleshok commented on packages/client/src/engine/Game.tsx
> +  loop = () => {
Для всех методов и полей лучше явно указать модификатор доступа public / private
поправь, пожалуйста, в этом класс и в классе пакмена

2023-09-07 21:48 UTC, IvanPeleshok approved these changes
Замечательная работа!
ПОздравляю, апрув!

2023-09-08 11:12 UTC, merged