Zubastu/16bit 57 настроить express для server side rendering без redux
ivanK333/pac-man pull request #55
Opened 2023-09-19 12:56 UTC by zubastu

### Какую задачу решаем

Установка зависимостей: - Установить Node.js, если он ещё не установлен. - Установить Express и другие необходимые пакеты, используя менеджер пакетов npm или yarn.

Создание основного сервера Express: - Создать файл server.ts или app.ts для настройки Express-сервера. - Импортировать необходимые модули и настроить базовый сервер Express. - Создать маршрут (route) для обработки запросов на главную страницу.

Настройка серверного рендеринга: - Импортировать React-компоненты и необходимые модули для серверного рендеринга. - Создать функцию-обработчик, которая будет отдавать рендеринг React-страницы. - В функции-обработчике использовать ReactDOMServer.renderToString() для рендеринга React-компонентов в строку.

Интеграция с Express: - Добавить серверный рендеринг в маршрут, который отвечает за главную страницу. - В функции-обработчике использовать метод res.send() для отправки HTML-страницы с рендерингом React на клиент.

Дополнительные настройки и обработка запросов: - Настроить статическую доставку клиентских ресурсов, таких как CSS- и JS-файлы.

Тестирование и отладка: - Запустить сервер Express и убедиться, что страница рендерится правильно. - Проверить, что все роуты и обработчики работают корректно. - Провести отладку возможных ошибок и исправить их.

### `для запуска node server с ssr-bubdle из корня проекта`

### `yarn run ssr-dev` - для сборки в режиме development 
### `yarn run ssr-prod` - для сборки production 

### Так же добавил логгеры ошибок и запросов, теперь можно открыть файл и посмотреть историю запросов, информацию и ошибки, файлы запиисываются при помощи бибилиотеки winston + winston express 

### названия файлов с логами `error.log` и `request.log` в корневой папке `server`

### Скриншоты/видяшка (если есть)
![image](https://github.com/ivanK333/pac-man/assets/79757684/82c9e857-bc1e-4adc-a374-63878aaaba0c)
![image](https://github.com/ivanK333/pac-man/assets/79757684/c8b58d91-0a36-4aa9-b475-225c9a889941)

2023-09-19 12:58 UTC, zubastu commented
Сейчас у нас проверка идет из данных в localStorage которого не существует при серверной сборке, необходимые правки - перенести хранение флага авторизации в куки

2023-09-19 23:11 UTC, zubastu commented
Временно захардкодил проверку авторизации пользователя, запросы проксированы, куки авторизации с апи яндекса приходят и првоеряются, данные пользователя доступны, авторизация регистрация изменение профиля и аватара проксирвоаны

2023-09-21 18:25 UTC, zubastu commented
Отключил хук useEventListener, оставил пока коментарии в коде.

2023-09-26 16:28 UTC, razuvaevcr approved these changes
Все замечательно! Проделана большая работа! Апрув

2023-09-27 17:57 UTC, Olegas requested changes
Добрый день. Есть ряд замечаний по коду. Написал отдельные комментарии

2023-09-27 17:57 UTC, Olegas commented on packages/client/src/hooks/useLocalStorage.ts
> +  const [value, setValue] = useState<null | string>(null);
Может лучше не ломать работу этого хука на клиенте а просто сделать что бы он не падал на сервере? Например проверить что local storage нету и не пытаться читать начальное значение. Можно использовать возможность передачи функции в useState для первичной инициализации

2023-09-27 18:12 UTC, zubastu commented on packages/client/src/pages/GameOver/GameOver.tsx
> +  }
document и window разныек вещи

2023-09-27 18:23 UTC, zubastu commented on packages/client/index.html
> +    <!--stylesheet-outlet-->
поправил

2023-09-27 18:29 UTC, zubastu commented on packages/client/src/pages/GameOver/GameOver.tsx
> +  }
Почему Вы считаете что useEffect при отсуствии window не сработает?

2023-09-27 19:25 UTC, Olegas commented on packages/client/src/pages/GameOver/GameOver.tsx
> +  }
Если у нас нет windows, значит мы на сервере. Если мы на сервере - у нас SSR. При SSR-построении useEffect не вызывается. Вот, например, статья: https://codewithhugo.com/react-useeffect-ssr/

2023-09-27 19:32 UTC, zubastu commented on packages/client/src/pages/GameOver/GameOver.tsx
> +  }
эффект для навешивания обработчика и он отрабатывает и снимает его если перйти на другой роут.

2023-09-27 19:41 UTC, Olegas commented on packages/client/src/pages/GameOver/GameOver.tsx
> +  }
Если hasWindow - выполняется useEventListener.
В противном случае (если нет window) будет выполнен useEffect. Но сам эффект не выполнится, потому что при серверном построении (а на сервере мы потому, что у нас нет window) - не выполняется (функция, которая указан в эффекте не будет вызвана).

2023-09-27 19:42 UTC, zubastu commented on packages/client/src/pages/GameOver/GameOver.tsx
> +  }
странно, я вообще сделал этот эффект для того чтобы приложение не рубилось на этапе сборки на сервере, так как там есть ссылка на window

2023-09-27 19:43 UTC, Olegas commented on packages/client/src/pages/GameOver/GameOver.tsx
> +  }
> эффект для навешивания обработчика и он отрабатывает и снимает его если перйти на другой роут при сборке ssr.

Это все происходит на клиенте. На клиенте есть window, hasWindow будет true, отработает useEventListener

2023-09-27 19:57 UTC, zubastu commented on packages/client/src/pages/GameOver/GameOver.tsx
> +  }
удалил код с эффектами

2023-09-27 20:33 UTC, zubastu commented on packages/client/src/hooks/useLocalStorage.ts
> +  const [value, setValue] = useState<null | string>(null);
Исправил работу хука, добавил проверку для начального значения

2023-09-27 20:34 UTC, zubastu commented on packages/client/src/utils/cookie.ts
> +}
я забыл удалить, я хотел заменить использвоангие local storage на cookie, но это не потребовалось

2023-09-28 12:16 UTC, Olegas requested changes
Появилась новая проблема. Написал по ней подробный комментарий

2023-09-28 12:16 UTC, Olegas commented on packages/client/src/hooks/useLocalStorage.ts
> +  if (typeof window === 'object' || typeof window !== 'undefined') {
Так нельзя делать, тут ошибка. Документация React говорит, что хуки нельзя добавлять под условия или в циклы. Потому что хуки в данном компоненте всегда должны работать в одном и том же порядке и в одном и том же количестве. Здесь хук оказался под условием - это нарушение требований документации. Проверки надо унести непосредственно в точки доступа к проблемным данным

2023-09-28 12:34 UTC, zubastu commented on packages/client/src/hooks/useLocalStorage.ts
> +  if (typeof window === 'object' || typeof window !== 'undefined') {
Исправил

2023-09-28 16:09 UTC, Olegas approved these changes
Работа принята. Спасибо!

2023-09-28 16:30 UTC, merged