add oauth
ivanK333/pac-man pull request #58
Opened 2023-09-29 12:52 UTC by PolinaKuksova2022

Добавлена OAuth-авторизация в проект.

После авторизации происходит редирект на страницу лендинга. Пока в  качестве redirect_uri используем http://localhost:3000. 

![image](https://github.com/ivanK333/pac-man/assets/108727043/1108fb0c-5938-409c-97be-6cc783885fa8)

2023-09-29 15:16 UTC, zubastu approved these changes
Авторизация работает, аппрув

2023-09-29 19:54 UTC, manshind requested changes
Оставил несколько комментариев (один важный про redirectUrl, и остальные некритичные)

2023-09-29 19:54 UTC, manshind commented on packages/client/src/constants/api.ts
> +export const REDIRECT_URI = 'http://localhost:3000';
такой путь будет работать только при локальной разработке, для продакшена его нужно менять.
это можно сделать либо через задание переменных окружения, либо собирать из window.location (для этого варианта нужны будут дополнительные проверки, что код запускается на клиенте, если у вас есть ssr).

2023-09-29 19:54 UTC, manshind commented on packages/client/src/components/OAuth/OAuth.tsx
> +  const OAuth = useCallback(async () => {
название функции не очень соответствует тому, что она делает (это только получение serviceId, а не сама авторизация).
ее можно назвать loadServiceId, например

2023-09-29 19:54 UTC, manshind commented on packages/client/src/controllers/AuthController.ts
> +      return error.response?.data?.reason;
тут лучше либо вообще не отлавливать ошибку и обработать там, где вызывается функция, либо полностью обрабатывать здесь (например, тот же самый console.log).
при успешном выполнении возвращается строка, и при ошибке тоже возвращается строка, из за этого просто будет неудобно проверять прошел ли запрос успешно или нет.

2023-09-29 19:54 UTC, manshind commented on packages/client/src/controllers/AuthController.ts
> +      return error.response?.data?.reason;
тут то же самое (либо обработать тут, либо вообще тут не ловить ошибку)

2023-10-03 11:35 UTC, PolinaKuksova2022 commented on packages/client/src/constants/api.ts
> +export const REDIRECT_URI = 'http://localhost:3000';
Пока нет своего домена, я сделала через window.location.origin

2023-10-03 11:35 UTC, PolinaKuksova2022 commented on packages/client/src/components/OAuth/OAuth.tsx
> +  const OAuth = useCallback(async () => {
Поменяла на loadServiceId

2023-10-03 11:36 UTC, PolinaKuksova2022 commented on packages/client/src/controllers/AuthController.ts
> +      return error.response?.data?.reason;
Исправила на console.log(error)

2023-10-03 11:36 UTC, PolinaKuksova2022 commented on packages/client/src/controllers/AuthController.ts
> +      return error.response?.data?.reason;
Исправила на console.log(error)

2023-10-03 17:04 UTC, manshind approved these changes

2023-10-04 07:07 UTC, merged