добавлен api лидерборда
ivanK333/pac-man pull request #60
Opened 2023-10-05 16:29 UTC by razuvaevcr

### Какую задачу решаем
Добавления api для лидерборда

### Скриншоты/видяшка (если есть)
-
### TBD (если есть)
-

2023-10-08 18:44 UTC, PolinaKuksova2022 approved these changes
Отличная работа!
Все работает, комментариев по коду нет.

2023-10-09 12:25 UTC, IvanPeleshok commented on packages/client/src/controllers/LeaderboardController.ts
> +    const { first_name, avatar } = await getUserInfo();
Если промис упадёт с исключением, то приложение выкинет его наружу
Предлагаю обработать через try / catch

2023-10-09 12:28 UTC, IvanPeleshok commented on packages/client/src/engine/GameCanvas.tsx
> +  // let spaceDisabled = false;
Предлаагю удалить неиспользуемый код (YAGNI)
https://web-creator.ru/articles/yagni

2023-10-09 12:31 UTC, IvanPeleshok commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +        {data.map((i) => (
Рекомендуется писать человекочитаемые переменные, ведь ваш тимейт должен понимать контекст переменной (хотя бы item)

2023-10-09 12:32 UTC, IvanPeleshok commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +  const [data, setData] = useState<leaderboardData>([]);
Давайте назовём переменную data, чтобы она передавала контекст своего применения

2023-10-09 12:33 UTC, IvanPeleshok commented on packages/client/src/api/leaderboard/leaderboard.ts
> +  const addUserToLeaderboard = async (data: AddUserData) =>
А что насчёт типа, который вернёт промис?
Собираетесь его описать сейчас или уже при внедрении хранилища redux / mobx и т.д?

2023-10-09 12:36 UTC, IvanPeleshok requested changes
Проделана огромная работа, отлично постарались!
Есть небольшие замечания, предлагаю доработать

Хорошего дня :)

2023-10-09 12:39 UTC, razuvaevcr commented on packages/client/src/engine/GameCanvas.tsx
> +  // let spaceDisabled = false;
Привет! 
Эта часть кода используется при тестировании смертей в dev режиме. Здесь была закоментирована, так как дает ошибку подсчета жизней в обработчике. По итогу, обработчик будет удален, но сейчас удобно воспроизводить определенное поведение или сценарии. 

Будет лучше убрать ее из этой ветки или оставить для дальнейших тестов?

2023-10-10 07:14 UTC, IvanPeleshok commented on packages/client/src/engine/GameCanvas.tsx
> +  // let spaceDisabled = false;
Привет

Давай оставим и напишем небольшой комментарий для чего это необходимо

2023-10-12 18:54 UTC, razuvaevcr commented on packages/client/src/api/leaderboard/leaderboard.ts
> +  const addUserToLeaderboard = async (data: AddUserData) =>
Будем писать его в следующем спринте при внедрении

2023-10-13 12:07 UTC, IvanPeleshok approved these changes
Замечательная работа, отлично поработали

Поздравляю, апрувчик

Хорошего дня :)

2023-10-13 12:50 UTC, merged