Zubastu/16bit 64 реализовать api для форума
ivanK333/pac-man pull request #61
Opened 2023-10-12 15:15 UTC by zubastu

### Какую задачу решаем
Реализация АПИ для работы с бд и разработка эндпоинтов для работы форума

В БД используется 3 Модели TopicModel MessageModel CommentModel

1. TopicModel - используется для получения всех топиков, создания, удаления и изменеия соддержания топика

2. MessageModel - испоьзуется для добавления сообщения в топик, удаления сообщения, изменения и получения всех сообщений относящихся к топику

3. CommentModel - используется для добавления комментариев к сообщениям, удаления комментария, изменения коментария, и получение всех комментариев для выбранного сообщения

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-10-15 18:10 UTC, PolinaKuksova2022 approved these changes
Хорошо продумал бд, реализация на высшем уровне!

2023-10-15 18:10 UTC, PolinaKuksova2022 commented on packages/client/src/constants/api.ts
> +export const API_URL = 'http://localhost:3005/api/v2';
Зачем изменил API_URL?

2023-10-15 18:10 UTC, PolinaKuksova2022 commented on packages/client/src/routes/Main/Main.tsx
> +//import startSW from '../../../startServiceWorker';
Почему отключил SW? не работает?

2023-10-15 18:11 UTC, zubastu commented on packages/client/src/constants/api.ts
> +export const API_URL = 'http://localhost:3005/api/v2';
потмоу что с клиента должны уходить запросы на сервер

2023-10-15 18:11 UTC, zubastu commented on packages/client/src/routes/Main/Main.tsx
> +//import startSW from '../../../startServiceWorker';
выдает много ошибок

2023-10-16 06:14 UTC, MIdkhat reviewed
Я весь код изучил когда к нему API клиента писал, все очень логично, было понятно что откуда брать и использовать. Отличная работа.

2023-10-16 06:50 UTC, ivanK333 approved these changes

2023-10-16 13:53 UTC, IvanPeleshok requested changes
Проделана огромная работа!
Отлично потрудились, приятно читать такой код

Есть парочка замечаний и вопросов, предлагаю доработать

Читать код из колбеков then / catch порой затруднительно, предлагаю использовать async / await + try / catch - выглядит намного приятнее

Хорошего дня :)

2023-10-16 13:53 UTC, IvanPeleshok commented on packages/client/src/constants/api.ts
> +export const API_URL = 'http://localhost:3005/api/v2';
Было бы отлично вынести данную константу в переменную окружения, чтобы было удобнее манипулировать (к примеру, когда будет хостинг или локальная разработка)

2023-10-16 13:53 UTC, IvanPeleshok commented on packages/server/forum/controllers/commentController.ts
> +      res.status(200).json(comment);
Статус создания ресурса 201
https://habr.com/ru/articles/736976/#:~:text=%D0%9C%D0%BD%D0%BE%D0%B3%D0%B8%D0%B5%20%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F%20%D0%BF%D0%BE%D0%B7%D0%B2%D0%BE%D0%BB%D1%8F%D1%8E%D1%82%20%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%B2%D0%B0%D1%82%D1%8C%20%D1%81%D1%83%D1%89%D0%BD%D0%BE%D1%81%D1%82%D0%B8%3A%20%D0%B0%D0%BA%D0%BA%D0%B0%D1%83%D0%BD%D1%82%D1%8B%2C%20%D0%B7%D0%B0%D0%BA%D0%B0%D0%B7%D1%8B%20%D0%B8%20%D1%82%D0%B0%D0%BA%20%D0%B4%D0%B0%D0%BB%D0%B5%D0%B5.%20%D0%92%20%D0%BE%D0%B1%D1%89%D0%B5%D0%BC%20%D1%81%D0%BB%D1%83%D1%87%D0%B0%D0%B5%20%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D1%8F%D0%B5%D1%82%D1%81%D1%8F%20HTTP%2D%D0%BA%D0%BE%D0%B4%20%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D1%8F%20200%2C%20%D0%B8%20%D1%8D%D1%82%D0%BE%D0%B3%D0%BE%20%D0%B2%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%20%D0%B4%D0%BE%D1%81%D1%82%D0%B0%D1%82%D0%BE%D1%87%D0%BD%D0%BE.%20%D0%9E%D0%B4%D0%BD%D0%B0%D0%BA%D0%BE%20%D0%BA%D0%BE%D0%B4%20201%20%D0%B1%D0%BE%D0%BB%D0%B5%D0%B5%20%D0%BA%D0%BE%D0%BD%D0%BA%D1%80%D0%B5%D1%82%D0%B5%D0%BD%20%D0%B8%20%D0%BF%D0%BE%D0%B4%D1%85%D0%BE%D0%B4%D0%B8%D1%82%20%D0%BB%D1%83%D1%87%D1%88%D0%B5%3A

2023-10-16 13:53 UTC, IvanPeleshok commented on packages/server/forum/init.ts
> +POSTGRES_USER=postgres
Полагаю, что эта информация избыточна (комментарии), для дев ветки

2023-10-16 13:53 UTC, IvanPeleshok commented on packages/server/forum/routes/routes.ts
Замечательно, что вынесли отдельный модуль

2023-10-16 13:53 UTC, IvanPeleshok commented on packages/server/forum/controllers/commentController.ts
> +    .then((comment) => {
Вижу, что все асинхронные вызовы резолвятся с помощью then / catch?

Было решено на уровне команды работать с промиссами именно так?

2023-10-16 13:53 UTC, IvanPeleshok commented on packages/server/forum/controllers/commentController.ts
> +      CommentModel.update(
Обычно работу с бд и остальными сайд-эффектами выносят в сервисы
Что-то такое: https://devtut.github.io/nodejs/route-controller-service-structure-for-expressjs.html#model-routes-controllers-services-code-structure
(Рекомендация)

2023-10-16 14:11 UTC, zubastu commented on packages/server/forum/controllers/commentController.ts
> +    .then((comment) => {
не вижк особых проблем с читаемостью, это обязательно к исправлению?

2023-10-16 14:12 UTC, zubastu commented on packages/server/forum/init.ts
> +POSTGRES_USER=postgres
эта информация для участников команды, чтобы было откуда брать данные для подключения

2023-10-16 14:13 UTC, zubastu commented on packages/server/forum/controllers/commentController.ts
> +      res.status(200).json(comment);
но тут и 200 код подходит

2023-10-16 14:17 UTC, zubastu commented on packages/server/forum/controllers/commentController.ts
> +    .then((comment) => {
это рекомендация или запрос к испралению?

2023-10-16 14:19 UTC, zubastu commented on packages/server/forum/controllers/commentController.ts
> +      CommentModel.update(
https://github.com/ivanK333/pac-man/pull/61#discussion_r1360690739
Он выдает много ошибок в редиме разработки, потому и отключил

2023-10-16 14:19 UTC, zubastu commented on packages/server/forum/init.ts
> +POSTGRES_USER=postgres
удалил

2023-10-16 15:24 UTC, IvanPeleshok commented on packages/server/forum/controllers/commentController.ts
> +    .then((comment) => {
Не, просто вопрос :)
Если вас устраивает, у меня нет возражений

2023-10-16 15:25 UTC, zubastu commented on packages/server/forum/controllers/commentController.ts
> +      CommentModel.update(
Я не вижу пока практического смысла делать обертку на sequlize - фактически это и есть сервис для работы с бд, делать еще одну абстракцию для абстракции?

2023-10-17 12:56 UTC, IvanPeleshok commented on packages/server/forum/controllers/commentController.ts
> +      CommentModel.update(
На данный момент в этом действительно нет смысла, но мы же хотим строить масштабируемую систему

2023-10-17 12:57 UTC, IvanPeleshok commented on packages/server/forum/controllers/commentController.ts
> +      CommentModel.update(
К примеру, захотите интегрировать бота или логгер, для этого отлично подойдёт сервис

2023-10-17 12:58 UTC, zubastu commented on packages/server/forum/controllers/commentController.ts
> +      CommentModel.update(
Логгер запросов есть)

2023-10-17 13:00 UTC, merged